### PR TITLE
Make the cfp more flexible

### PR DESCRIPTION
**Pull request by AEtherC0r3**
Up until now the cfp only accepts requests for events(proposals), this pr modifies it so it can be used for more things (like tracks and booths), while providing backwards compatibility.
* The column cfp_type allows as to have different kinds of cfps for the same conference
* The constant Cfp::TYPES defines the allowed values for cfp_type
* The method Cfp#open? is the equivalent of the older Program#cfp_open? for a specific cfp
* An index view has been added for the cfps
* The Cfp#show view was refactored to use partials, so each type of cfp can have it's own partial

### CODE REVIEW

File: spec/models/cfp_spec.rb [hunk 1]
```diff
@@ -1,8 +1,24 @@
...
+        expect(conference.program.cfps.for_events).to be_a Cfp
+        expect(conference.program.cfps.for_events.cfp_type).to eq('events')
+      end
+    end
+  end
+
+  describe 'validations' do
+    it { is_expected.to validate_presence_of(:cfp_type) }
+    it { is_expected.to validate_inclusion_of(:cfp_type).in_array(Cfp::TYPES) }
+    it { is_expected.to validate_uniqueness_of(:cfp_type).scoped_to(:program_id) }
```
Comment (sayalilunkad) [inline spec/models/cfp_spec.rb]: Just after a brief look try using validate_uniqueness_of(:cfp_type).scoped_to(:program_id).case_insensitive
Will review the whole PR soon.

File: app/models/program.rb [hunk 2]
```diff
@@ -163,6 +163,23 @@ def any_event_for_this_date?(date)
...
+  # * +ActiveRecord+ -> The program's cfp with cfp_type == 'events'
+  def cfp
+    return nil if cfps.for_events.blank?
+    cfps.for_events
+  end
+
+  ##
+  # ====Returns
+  # * +Array+ -> The types of cfps for which a cfp doesn't exist yet
+  def available_cfp_types
```
Comment (differentreality) [inline app/models/program.rb]: I would rename this to something that is easier to associate with the result we get (the remaining types for which we can create a cfp)

**Comment by differentreality** [comment]
> undefined method `validate_inclusion_of' for #<RSpec::ExampleGroups::Cfp::Validations:0x0000000d77f1c0>

error should be fixed if you update shoulda-matchers gem to version 2.8

Conference registration error seems to be an invalid failure, that should be fixed when travis runs again.

I still haven't figured out why we are getting the test failure from `validate_uniqueness_of(:cfp_type).scoped_to(:program_id).case_insensitive`, so for now let's fix it by checking if program exists when validating.

**Comment by differentreality** [comment]
@sayalilunkad have you reviewed this? 
We should be able to bring it to a mergeable state, and merge it, in the next few days. 
To that end, @AEtherC0r3 after rebasing & submitting the travis fix, so that we can review, work on the haml lint errors as well.

**Comment by sayalilunkad** [comment]
@differentreality yes I have tested it out and it seems to work as expected. As for the failing travis tests I think `validate_uniqueness_of(:cfp_type).scoped_to(:program_id).case_insensitive` is also a bug. But other than that it looks fine.

File: app/views/admin/cfps/_form.html.haml [hunk 3]
```diff
@@ -4,8 +4,9 @@
       %h1 Call for Papers
 .row
   .col-md-8
-    = semantic_form_for(@cfp, url: admin_conference_program_cfp_path(@conference.short_title), html: {multipart: true}) do |f|
+    = semantic_form_for(@cfp, url: (@cfp.new_record? ? admin_conference_program_cfps_path : admin_conference_program_cfp_path(@conference.short_title, @cfp)), html: {multipart: true}) do |f|
       = f.input :start_date, as: :string, input_html: { id: 'registration-period-start-datepicker', start_date: @conference.start_date, end_date: @conference.end_date, readonly: 'readonly' }
       = f.input :end_date, as: :string, input_html: { id: 'registration-period-end-datepicker', readonly: 'readonly' }
+      = f.input :cfp_type, as: :select, collection: (@cfp.new_record? ? @program.remaining_cfp_types : @program.remaining_cfp_types.insert(0, @cfp.cfp_type)).map {|type| ["#{type.capitalize}", type]}, include_blank: false, label: 'Type', input_html: { class: 'select-help-toggle' }
```
Comment (differentreality) [inline app/views/admin/cfps/_form.html.haml]: Let's try to make this more readable

File: app/views/admin/cfps/index.html.haml [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+                = cfp.start_date.strftime('%A, %B %-d. %Y')
+              %td
+                = cfp.end_date.strftime('%A, %B %-d. %Y')
+              %td
+                = pluralize(cfp.remaining_days, 'day')
+              %td
+                .btn-group
+                  = link_to 'Edit', edit_admin_conference_program_cfp_path(@conference.short_title, cfp.id), method: :get, class: 'btn btn-primary'
+                  = link_to 'Delete', admin_conference_program_cfp_path(@conference.short_title, cfp.id), method: 'delete', class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete the CfP?' }
+- if @program.remaining_cfp_types.length > 0
```
Comment (differentreality) [inline app/views/admin/cfps/index.html.haml]: Add an ability so that:
1) This line becomes something like i`f can? [:new, :create] @program.cfps.new` (alternatively you could still be showing the button, just make it disabled with a title saying that it is not possible to create any other type of CfP for the conference
2) You also authorize the access to the action new/create so that with load_and_authorize in controller it will not be possible to access this page at all

**Comment by differentreality** [comment]
@AEtherC0r3 let's focus on finalizing this PR first.

File: spec/models/program_spec.rb [hunk 5]
```diff
@@ -240,4 +240,23 @@
     end
   end
 
+  describe '#cfp' do
+    it 'return the cfp for events' do
```
Comment (differentreality) [inline spec/models/program_spec.rb]: Returns

File: spec/models/conference_spec.rb [hunk 6]
```diff
@@ -1176,122 +1174,122 @@
...
       expect(subject.get_submissions_per_week).to eq([1, 1, 1, 2])
     end
 
     it 'pads right' do
-      cfp = create(:cfp)
+      cfp = create(:cfp, program: subject.program)
       cfp.start_date = Date.new(2014, 05, 26)
       cfp.end_date = Date.new(2014, 05, 26) + 21
-      subject.program.cfp = cfp
+      cfp.save
```
Comment (differentreality) [inline spec/models/conference_spec.rb]: Save!

File: app/models/ability.rb [hunk 7]
```diff
@@ -208,7 +213,7 @@ def signed_in_with_cfp_role(user)
     can :manage, Room, venue: { conference_id: conf_ids_for_cfp }
     can :show, Venue, conference_id: conf_ids_for_cfp
     can :show, Commercial, commercialable_type: 'Venue', commercialable_id: Venue.where(conference_id: conf_ids_for_cfp).pluck(:id)
-    can :manage, Cfp, program: { conference_id: conf_ids_for_cfp }
+    can :manage, Cfp, program: { conference_id: conf_ids_for_cfp}
```
Comment (differentreality) [inline app/models/ability.rb]: Keep the space inside the curly brackets

**Comment by differentreality** [comment]
Go ahead and squash after you fix the failures 😊

**Comment by AEtherC0r3** [comment]
Cfp#new


Cfp#index


Cfp#show for events

**Comment by differentreality** [comment]
Looks nice :+1: Let's get it in :tada:
